import express, { Express, Request, Response } from "express";
import dotenv from "dotenv";
import { GHL } from "./ghl";
import { json } from "body-parser";
import { createShiftLog,getAssignmentRecordId,getLocationGoal,getPerformanceRollup,getReviewQueue,getSellerShiftLogs,
  initializeAssignmentIndex,initializePerformanceStore,reviewShiftLog,upsertAssignmentIndex,upsertLocationGoal } from "./db";
const path=__dirname+"/ui/dist/"; dotenv.config(); const app:Express=express(); app.use(json({type:"application/json"})); app.use(express.static(path));
const ghl=new GHL(); const port=process.env.PORT; const SPOKE_COMPANY_ID="NUAR0gljpx3i4RfDQPCf";
const MANAGER_ROLES=new Set(["sales_manager","general_manager","regional_manager","owner"]);
const PROVISION_ROLES=new Set(["general_manager","regional_manager","owner"]);
const LOCATION_GOAL_WRITE_ROLES=new Set(["general_manager","regional_manager","owner"]);
function isActive(v:unknown){return String(v??"").trim().toLowerCase()==="yes"}
function normalizeRole(v:unknown){return String(v??"").trim().toLowerCase().replace(/[\s-]+/g,"_")}
async function ensureLocationToken(activeLocation:string){if(ghl.checkInstallationExists(activeLocation))return; const c=ghl.model.installationObjects[SPOKE_COMPANY_ID]; if(!c||c.userType!=="Company")throw Object.assign(new Error("No OAuth token available for this location"),{statusCode:403}); await ghl.getLocationTokenFromCompanyToken(SPOKE_COMPANY_ID,activeLocation); if(!ghl.checkInstallationExists(activeLocation))throw Object.assign(new Error("Location token exchange produced no token"),{statusCode:403})}
async function getRecordById(loc:string,id:string){const r=await ghl.requests(loc).get(`/objects/custom_objects.mpp_user_assignment/records/${id}`,{headers:{Version:"v3"}});return r.data?.record??null}
function decryptTrustedIdentity(key:string){if(!key)throw Object.assign(new Error("SSO key required"),{statusCode:400});let s:any;try{s=ghl.decryptSSOData(key)}catch{throw Object.assign(new Error("Invalid SSO key"),{statusCode:401})}const{userId,activeLocation}=s;if(!userId||!activeLocation)throw Object.assign(new Error("SSO data missing required identity fields"),{statusCode:401});return{ssoData:s,userId,activeLocation}}
async function resolveTrustedAssignment(key:string){const i=decryptTrustedIdentity(key);await ensureLocationToken(i.activeLocation);const recordId=await getAssignmentRecordId(i.activeLocation,i.userId);if(!recordId)return{...i,assignmentFound:false};const r=await getRecordById(i.activeLocation,recordId);if(!r||r.properties?.ghl_user_id!==i.userId)return{...i,assignmentFound:false};return{...i,assignmentFound:true,assignment:{recordId,mpp_role:normalizeRole(r.properties?.mpp_role),scope_type:String(r.properties?.scope_type??"").trim().toLowerCase(),active:r.properties?.active??null,assignment_name:r.properties?.assignment_name??null,ghl_user_id:r.properties?.ghl_user_id??null}}}
function sendSafeError(res:Response,e:any,f="request_failed"){const s=e?.statusCode??500;console.error("[MPP] request error",{status:s,message:e?.message??"unknown"});return res.status(s).json({error:e?.message??f})}
function validMonth(v:any){return /^\d{4}-\d{2}$/.test(String(v??""))}
function monthBounds(month:string){const[y,m]=month.split("-").map(Number);const startDate=`${month}-01`;const endDate=new Date(Date.UTC(y,m,1)).toISOString().slice(0,10);return{startDate,endDate}}
function pacing(month:string,target:number,actual:number){const[y,m]=month.split("-").map(Number);const days=new Date(Date.UTC(y,m,0)).getUTCDate();const today=new Date();let elapsed=days;if(today.getUTCFullYear()===y&&today.getUTCMonth()+1===m)elapsed=Math.min(days,today.getUTCDate());else if(Date.UTC(today.getUTCFullYear(),today.getUTCMonth(),1)<Date.UTC(y,m-1,1))elapsed=0;const expected=target*(elapsed/days);return{daysInMonth:days,elapsedDays:elapsed,expectedToDate:Number(expected.toFixed(2)),actual,variance:Number((actual-expected).toFixed(2)),percentOfGoal:target>0?actual/target:0}}
app.get("/authorize-handler",async(req,res)=>{await ghl.authorizationHandler(req.query.code as string);res.redirect("https://app.gohighlevel.com/")});
app.post("/decrypt-sso",async(req,res)=>{try{return res.send(ghl.decryptSSOData(req.body?.key))}catch{return res.status(400).send("Invalid Key")}});
app.get("/oauth/callback",async(req,res)=>{if(!req.query.code)return res.status(200).send("MPP OAuth Callback Received");try{await ghl.authorizationHandler(req.query.code as string);return res.status(200).send("MPP OAuth Installation Complete")}catch(e:any){console.error("[MPP] OAuth callback failed",{message:e?.message??"unknown"});return res.status(500).send("MPP OAuth token exchange/storage failed")}});
app.get("/oauth/token-status",(_req,res)=>{const l="e44pA2hEK8BXwer0eNYB",i=ghl.model.installationObjects[l],k=Object.keys(ghl.model.installationObjects);res.json({tokenAvailable:ghl.checkInstallationExists(l),locationId:i?.locationId??null,companyId:i?.companyId??null,userType:i?.userType??null,expires_in:i?.expires_in??null,refreshTokenPresent:!!ghl.model.getRefreshToken(l),installationObjectsKeys:k,storedKey:k[0]??null})});
app.post("/assignment-context",async(req,res)=>{try{const v:any=await resolveTrustedAssignment(req.body?.key);if(!v.assignmentFound)return res.json({trustedUserId:v.userId,activeLocation:v.activeLocation,tokenVerified:true,assignmentFound:false,assignment:null,capabilities:[]});const r=v.assignment.mpp_role,a=isActive(v.assignment.active);const capabilities=a?["view_shell",...(r==="seller"?["submit_shift","view_self"]:[]),...(MANAGER_ROLES.has(r)?["view_location","review_logs"]:[]),...(PROVISION_ROLES.has(r)?["provision_assignments"]:[]),...(LOCATION_GOAL_WRITE_ROLES.has(r)?["manage_location_goal"]:[])]:[];return res.json({trustedUserId:v.userId,activeLocation:v.activeLocation,tokenVerified:true,assignmentFound:true,assignment:v.assignment,capabilities})}catch(e:any){return sendSafeError(res,e,"assignment_lookup_failed")}});
app.post("/admin/assignment-provision",async(req,res)=>{try{const{key,recordId}=req.body||{};if(!recordId||typeof recordId!=="string")return res.status(400).json({error:"recordId required"});const i=decryptTrustedIdentity(key);await ensureLocationToken(i.activeLocation);const t=await getRecordById(i.activeLocation,recordId),target=t?.properties?.ghl_user_id;if(!t||!target)return res.status(400).json({error:"Target assignment record is invalid"});if(!isActive(t.properties?.active))return res.status(400).json({error:"Target assignment record is inactive"});const existing=await getAssignmentRecordId(i.activeLocation,i.userId);let mode:"self"|"admin"="self";if(!existing){if(target!==i.userId)return res.status(403).json({error:"Self-provisioning requires your own assignment record"})}else{const c:any=await resolveTrustedAssignment(key);if(!c.assignmentFound||!isActive(c.assignment.active))return res.status(403).json({error:"Active MPP assignment required"});if(!PROVISION_ROLES.has(c.assignment.mpp_role))return res.status(403).json({error:"Assignment provisioning not permitted"});mode="admin"}await upsertAssignmentIndex(i.activeLocation,target,recordId);return res.json({provisioned:true,mode,locationId:i.activeLocation,recordId,assignment:{assignment_name:t.properties?.assignment_name??null,ghl_user_id:target,mpp_role:normalizeRole(t.properties?.mpp_role),scope_type:t.properties?.scope_type??null,active:t.properties?.active??null}})}catch(e:any){return sendSafeError(res,e,"assignment_provision_failed")}});
app.post("/seller/shift-log",async(req,res)=>{try{const v:any=await resolveTrustedAssignment(req.body?.key);if(!v.assignmentFound||!isActive(v.assignment.active)||v.assignment.mpp_role!=="seller")return res.status(403).json({error:"Seller role required"});const o=Number(req.body?.opportunities),s=Number(req.body?.membershipsSold),d=String(req.body?.shiftDate??"");if(!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isInteger(o)||o<0||!Number.isInteger(s)||s<0||s>o)return res.status(400).json({error:"Invalid shift values"});const log=await createShiftLog({locationId:v.activeLocation,sellerUserId:v.userId,sellerName:v.assignment.assignment_name||v.ssoData.userName||"Seller",assignmentRecordId:v.assignment.recordId,shiftDate:d,opportunities:o,membershipsSold:s,notes:String(req.body?.notes??"").slice(0,2000)});return res.status(201).json({created:true,log})}catch(e:any){return sendSafeError(res,e)}});
app.post("/seller/shift-logs",async(req,res)=>{try{const v:any=await resolveTrustedAssignment(req.body?.key);if(!v.assignmentFound||!isActive(v.assignment.active))return res.status(403).json({error:"Active MPP assignment required"});return res.json({logs:await getSellerShiftLogs(v.activeLocation,v.userId,30)})}catch(e:any){return sendSafeError(res,e)}});
app.post("/manager/review-queue",async(req,res)=>{try{const v:any=await resolveTrustedAssignment(req.body?.key);if(!v.assignmentFound||!isActive(v.assignment.active)||!MANAGER_ROLES.has(v.assignment.mpp_role))return res.status(403).json({error:"Manager role required"});return res.json({logs:await getReviewQueue(v.activeLocation)})}catch(e:any){return sendSafeError(res,e)}});
app.post("/manager/review-shift",async(req,res)=>{try{const v:any=await resolveTrustedAssignment(req.body?.key);if(!v.assignmentFound||!isActive(v.assignment.active)||!MANAGER_ROLES.has(v.assignment.mpp_role))return res.status(403).json({error:"Manager role required"});if(!req.body?.logId||!["verified","rejected"].includes(req.body?.decision))return res.status(400).json({error:"Valid logId and decision required"});const log=await reviewShiftLog({locationId:v.activeLocation,logId:String(req.body.logId),reviewerUserId:v.userId,decision:req.body.decision});return log?res.json({reviewed:true,log}):res.status(409).json({error:"Shift log is not pending or was not found"})}catch(e:any){return sendSafeError(res,e)}});
app.post("/performance/rollup",async(req,res)=>{try{const v:any=await resolveTrustedAssignment(req.body?.key);if(!v.assignmentFound||!isActive(v.assignment.active))return res.status(403).json({error:"Active MPP assignment required"});const month=validMonth(req.body?.month)?String(req.body.month):new Date().toISOString().slice(0,7);const{startDate,endDate}=monthBounds(month);const sellerUserId=v.assignment.mpp_role==="seller"?v.userId:undefined;if(!sellerUserId&&!MANAGER_ROLES.has(v.assignment.mpp_role))return res.status(403).json({error:"Performance view not permitted"});const r=await getPerformanceRollup({locationId:v.activeLocation,startDate,endDate,sellerUserId});const o=Number(r.totals?.opportunities??0),s=Number(r.totals?.memberships_sold??0);return res.json({month,scope:sellerUserId?"self":"location",totals:{...r.totals,conversionRate:o>0?s/o:0},sellers:r.sellers.map((x:any)=>({...x,conversionRate:Number(x.opportunities)>0?Number(x.memberships_sold)/Number(x.opportunities):0}))})}catch(e:any){return sendSafeError(res,e)}});
/* P026A: location monthly goal. GM/RM/Owner write; every active assigned location user may read. */
app.post("/goals/location",async(req,res)=>{try{const v:any=await resolveTrustedAssignment(req.body?.key);if(!v.assignmentFound||!isActive(v.assignment.active))return res.status(403).json({error:"Active MPP assignment required"});const month=validMonth(req.body?.month)?String(req.body.month):new Date().toISOString().slice(0,7);const goal=await getLocationGoal(v.activeLocation,month);const{startDate,endDate}=monthBounds(month);const perf=await getPerformanceRollup({locationId:v.activeLocation,startDate,endDate});const actual=Number(perf.totals?.memberships_sold??0);return res.json({month,goal,pace:goal?pacing(month,Number(goal.memberships_target),actual):null})}catch(e:any){return sendSafeError(res,e,"location_goal_failed")}});
app.post("/goals/location/set",async(req,res)=>{try{const v:any=await resolveTrustedAssignment(req.body?.key);if(!v.assignmentFound||!isActive(v.assignment.active)||!LOCATION_GOAL_WRITE_ROLES.has(v.assignment.mpp_role))return res.status(403).json({error:"Location goal management not permitted"});const month=String(req.body?.month??""),m=Number(req.body?.membershipsTarget),c=Number(req.body?.conversionTarget);if(!validMonth(month)||!Number.isInteger(m)||m<0||!Number.isFinite(c)||c<0||c>1)return res.status(400).json({error:"Valid month, memberships target, and conversion target required"});const goal=await upsertLocationGoal({locationId:v.activeLocation,month,membershipsTarget:m,conversionTarget:c,setByUserId:v.userId});return res.json({saved:true,goal})}catch(e:any){return sendSafeError(res,e,"location_goal_save_failed")}});
app.get("/",(_req,res)=>res.sendFile(path+"index.html"));
async function start(){try{const hydratedCount=await ghl.initialize();const assignmentIndexCount=await initializeAssignmentIndex();await initializePerformanceStore();console.log("[P019A] OAuth store ready",{hydratedCount});console.log("[P019B] Assignment index ready",{assignmentIndexCount});console.log("[P026A] Location goals ready");app.listen(port,()=>console.log(`GHL app listening on port ${port}`))}catch(e:any){console.error("[MPP] startup failed",{message:e?.message??"unknown"});process.exit(1)}}start();
