import { randomUUID } from "node:crypto";
import { parseAverageCount, parseCanonicalReportInput, requireText, validateGoal, isMonday } from "./location-performance";
import { correctLocationReport, getAverageSetting, getEffectiveGoals, getLocationReport, getLocationReportHistory, getLocationSummary, getPrefill, getReportEvents, runV1BIntegrityProof, setAverageSetting, setLocationGoalV1, submitLocationReport } from "./location-performance-store";

const READ_ROLES=new Set(["general_manager","regional_manager","owner"]);
function send(res:any,e:any,code="location_performance_failed"){const status=e?.statusCode??500;console.error("[V1B] request error",{status,code,message:e?.message??"unknown"});return res.status(status).json({error:e?.message??code});}
function actionId(v:any){return requireText(v,"Action ID",100);}
function version(v:any,label="Expected version"){if(typeof v!=="number"||!Number.isInteger(v)||v<0)throw Object.assign(new Error(label+" must be a non-negative integer"),{statusCode:400});return v;}
export function registerLocationPerformanceRoutes(app:any,deps:any){
 async function viewer(body:any,write=false){const v=await deps.resolveTrustedAssignment(body?.key);if(!v.assignmentFound||!deps.isActive(v.assignment.active))throw Object.assign(new Error("Active MPP assignment required"),{statusCode:403});if(write?v.assignment.mpp_role!=="general_manager":!READ_ROLES.has(v.assignment.mpp_role))throw Object.assign(new Error(write?"General Manager access required":"Location Performance access requires manager role"),{statusCode:403});const locationId=await deps.resolveAuthorizedLocation(v,body?.selectedScopeLocation);return {v,locationId,actorId:v.userId,actorName:v.assignment.assignment_name||v.ssoData?.userName||"Manager"};}
 app.post("/location-performance/reports/submit",async(req:any,res:any)=>{try{const x=await viewer(req.body,true),input:any=parseCanonicalReportInput(req.body);input.priorReportId=req.body?.priorReportId?requireText(req.body.priorReportId,"Prior report ID",100):null;input.prefilledBeginningActiveMemberships=req.body?.prefilledBeginningActiveMemberships??null;if(input.priorReportId&&!Number.isSafeInteger(input.prefilledBeginningActiveMemberships))throw Object.assign(new Error("Prefilled Beginning Active Memberships must accompany prior report"),{statusCode:400});return res.json(await submitLocationReport({...x,input,actionId:actionId(req.body?.actionId)}));}catch(e){return send(res,e);}});
 app.post("/location-performance/reports/correct",async(req:any,res:any)=>{try{const x=await viewer(req.body,true),input=parseCanonicalReportInput(req.body),reason=requireText(req.body?.reason,"Correction reason",1000);return res.json(await correctLocationReport({...x,input,reportId:requireText(req.body?.reportId,"Report ID",100),reason,expectedVersion:version(req.body?.expectedVersion),actionId:actionId(req.body?.actionId)}));}catch(e){return send(res,e);}});
 app.post("/location-performance/reports/history",async(req:any,res:any)=>{try{const x=await viewer(req.body);return res.json(await getLocationReportHistory(x.locationId,Number(req.body?.page)||1,Number(req.body?.pageSize)||20));}catch(e){return send(res,e);}});
 app.post("/location-performance/reports/detail",async(req:any,res:any)=>{try{const x=await viewer(req.body),reportId=requireText(req.body?.reportId,"Report ID",100),report=await getLocationReport(x.locationId,reportId);if(!report)return res.status(404).json({error:"Report not found"});return res.json({report,events:await getReportEvents(x.locationId,reportId)});}catch(e){return send(res,e);}});
 app.post("/location-performance/reports/prefill",async(req:any,res:any)=>{try{const x=await viewer(req.body),weekStart=requireText(req.body?.weekStart,"Week Start",10);if(!isMonday(weekStart))return res.status(400).json({error:"Week Start must be a valid Monday"});return res.json({prefill:await getPrefill(x.locationId,weekStart)});}catch(e){return send(res,e);}});
 app.post("/location-performance/summary",async(req:any,res:any)=>{try{const x=await viewer(req.body);return res.json({summary:await getLocationSummary(x.locationId,req.body?.reportId?String(req.body.reportId):undefined)});}catch(e){return send(res,e);}});
 app.post("/location-performance/goals",async(req:any,res:any)=>{try{const x=await viewer(req.body),weekStart=requireText(req.body?.weekStart,"Week Start",10);if(!isMonday(weekStart))return res.status(400).json({error:"Week Start must be a valid Monday"});return res.json({goals:await getEffectiveGoals(x.locationId,weekStart)});}catch(e){return send(res,e);}});
 app.post("/location-performance/goals/set",async(req:any,res:any)=>{try{const x=await viewer(req.body,true),g=validateGoal(req.body?.goalType,req.body?.value,req.body?.currency),effectiveFrom=requireText(req.body?.effectiveFrom,"Effective week",10);if(!isMonday(effectiveFrom))return res.status(400).json({error:"Effective week must be a valid Monday"});return res.json({goal:await setLocationGoalV1({...x,...g,effectiveFrom,expectedVersion:req.body?.expectedVersion==null?null:version(req.body.expectedVersion),actionId:actionId(req.body?.actionId)})});}catch(e){return send(res,e);}});
 app.post("/location-performance/average-settings",async(req:any,res:any)=>{try{const x=await viewer(req.body);return res.json({setting:await getAverageSetting(x.locationId)});}catch(e){return send(res,e);}});
 app.post("/location-performance/average-settings/set",async(req:any,res:any)=>{try{const x=await viewer(req.body,true);return res.json({setting:await setAverageSetting({...x,reportCount:parseAverageCount(req.body?.reportCount),expectedVersion:version(req.body?.expectedVersion),actionId:actionId(req.body?.actionId)})});}catch(e){return send(res,e);}});
 app.post("/location-performance/locations/glance",async(req:any,res:any)=>{try{const base=await deps.resolveTrustedAssignment(req.body?.key);if(!base.assignmentFound||!deps.isActive(base.assignment.active)||!READ_ROLES.has(base.assignment.mpp_role))return res.status(403).json({error:"Location Performance access requires manager role"});const requested=Array.isArray(req.body?.locationIds)&&req.body.locationIds.length?req.body.locationIds:[req.body?.selectedScopeLocation??base.activeLocation];const unique=[...new Set(requested.map((v:any)=>String(v).trim()).filter(Boolean))].slice(0,100);const locations=[];for(const id of unique){const authorized=await deps.resolveAuthorizedLocation(base,id);locations.push({locationId:authorized,summary:await getLocationSummary(authorized)});}return res.json({locations});}catch(e){return send(res,e);}});
 app.post("/diagnostics/v1b-integrity",async(req:any,res:any)=>{try{
  const testLocation="aGn7Uf2qec6eTb9M6k1K";
  if(process.env.RENDER_SERVICE_NAME!=="mpp-v1-staging")return res.status(404).json({error:"Not found"});
  const base=await deps.resolveTrustedAssignment(req.body?.key);
  if(!base.assignmentFound||!deps.isActive(base.assignment.active)||base.activeLocation!==testLocation)return res.status(403).json({error:"Scope/Test active assignment required"});
  let scopeDenied=false;try{await deps.resolveAuthorizedLocation(base,"v1b01-unauthorized-location");}catch{scopeDenied=true;}
  const result=await runV1BIntegrityProof(testLocation,scopeDenied);
  console.log("[V1B] integrity proof",{passed:result.passed,checks:result.checks,locationId:testLocation,secretValuesLogged:false});
  return res.json(result);
 }catch(e){return send(res,e,"v1b_integrity_failed");}});
}
