import { Express, Response } from "express";
import { changeAccessState, createSetupRequest, getPersonDetail, listPeople, seedV1TestOrganization, validateSetupReadiness } from "./people-store";
import { changePersonRelationship, getPeopleLookups, invitePerson } from "./people-admin-store";
import { completeV1FixtureMatrix } from "./people-fixtures";
import { assertPeopleMutationAllowed, normalizeResponsibility, requireActionId } from "./people-policy";

function safeError(res:Response,error:any){const status=error?.statusCode??500;console.error("[V1C] request error",{status,code:error?.code??"unknown",message:error?.message??"unknown"});return res.status(status).json({error:error?.message??"request_failed",code:error?.code??"request_failed"});}
export function registerPeopleRoutes(app:Express,deps:{resolveTrustedAssignment:(key:string)=>Promise<any>;resolveAuthorizedLocation:(viewer:any,location?:unknown)=>Promise<string>;isActive:(value:unknown)=>boolean}){
 async function reader(body:any){const viewer=await deps.resolveTrustedAssignment(body?.key);if(!viewer.assignmentFound||!deps.isActive(viewer.assignment.active))throw Object.assign(new Error("Active MPP assignment required"),{statusCode:403});const role=normalizeResponsibility(viewer.assignment.mpp_role);if(!["general_manager","regional_manager","owner"].includes(role))throw Object.assign(new Error("People & Access is not permitted"),{statusCode:403});const locationId=await deps.resolveAuthorizedLocation(viewer,body?.selectedScopeLocation);return {viewer,role,locationId};}
 app.post("/people",async(req,res)=>{try{const {locationId}=await reader(req.body);return res.json({locationId,people:await listPeople(locationId)});}catch(e){return safeError(res,e);}});
 app.post("/people/lookups",async(req,res)=>{try{const {locationId}=await reader(req.body);const result=await getPeopleLookups(locationId);return result?res.json(result):res.status(404).json({error:"Organization context not found"});}catch(e){return safeError(res,e);}});
 app.post("/people/detail",async(req,res)=>{try{const {locationId}=await reader(req.body);const detail=await getPersonDetail(String(req.body?.personId??""));return detail&&detail.locations.some((x:any)=>x.location_id===locationId)?res.json(detail):res.status(404).json({error:"Person not found"});}catch(e){return safeError(res,e);}});
 app.post("/people/invite",async(req,res)=>{try{const {viewer,role,locationId}=await reader(req.body);const lookups=await getPeopleLookups(locationId);if(!lookups)return res.status(404).json({error:"Organization context not found"});const target=normalizeResponsibility(req.body?.primaryResponsibility);assertPeopleMutationAllowed({actor:role,target,allowRmManageGms:Boolean(lookups.governance.allow_rm_manage_gms),actorHasLocation:true,targetLocationInActorScope:true});const locationIds=Array.isArray(req.body?.locationIds)?req.body.locationIds.map(String):[locationId];if(locationIds.some((id:string)=>!lookups.locations.some((x:any)=>x.location_id===id)))return res.status(403).json({error:"Location access is outside your organization"});return res.status(201).json(await invitePerson({organizationId:lookups.organizationId,displayName:String(req.body?.displayName??"").trim(),emailAlias:String(req.body?.emailAlias??"").trim(),responsibility:target,locationIds,actionId:requireActionId(req.body?.actionId),actorId:viewer.userId,actorName:viewer.assignment.assignment_name||viewer.ssoData.userName||"Manager"}));}catch(e){return safeError(res,e);}});
 app.post("/people/relationships",async(req,res)=>{try{const {viewer,role,locationId}=await reader(req.body);const detail=await getPersonDetail(String(req.body?.personId??""));if(!detail)return res.status(404).json({error:"Person not found"});const lookups=await getPeopleLookups(locationId);const target=normalizeResponsibility(detail.person.responsibility);assertPeopleMutationAllowed({actor:role,target,allowRmManageGms:Boolean(lookups?.governance?.allow_rm_manage_gms),actorHasLocation:true,targetLocationInActorScope:detail.locations.some((x:any)=>x.location_id===locationId)});const kind=String(req.body?.kind??"");if(!["responsibility","location_access","team_management","team_visibility","reporting_eligibility"].includes(kind))return res.status(400).json({error:"Relationship kind is invalid"});const state=String(req.body?.state??"active");if(!["active","inactive"].includes(state))return res.status(400).json({error:"Relationship state is invalid"});return res.json(await changePersonRelationship({personId:String(req.body.personId),kind,state,locationId:req.body?.locationId?String(req.body.locationId):locationId,teamId:req.body?.teamId?String(req.body.teamId):null,responsibility:kind==="responsibility"?normalizeResponsibility(req.body?.primaryResponsibility):null,expectedVersion:Number(req.body?.expectedVersion),actionId:requireActionId(req.body?.actionId),actorId:viewer.userId,actorName:viewer.assignment.assignment_name||viewer.ssoData.userName||"Manager"}));}catch(e){return safeError(res,e);}});
 app.post("/people/access-state",async(req,res)=>{try{const {viewer,role,locationId}=await reader(req.body);const detail=await getPersonDetail(String(req.body?.personId??""));if(!detail)return res.status(404).json({error:"Person not found"});const target=normalizeResponsibility(detail.person.responsibility);const lookups=await getPeopleLookups(locationId);assertPeopleMutationAllowed({actor:role,target,allowRmManageGms:Boolean(lookups?.governance?.allow_rm_manage_gms),actorHasLocation:true,targetLocationInActorScope:detail.locations.some((x:any)=>x.location_id===locationId)});const state=String(req.body?.state);if(!["active","inactive"].includes(state))return res.status(400).json({error:"Active or inactive state required"});return res.json(await changeAccessState({personId:String(req.body.personId),state,expectedVersion:Number(req.body?.expectedVersion),actionId:requireActionId(req.body?.actionId),actorId:viewer.userId,actorName:viewer.assignment.assignment_name||viewer.ssoData.userName||"Manager",reason:String(req.body?.reason??"").slice(0,1000)}));}catch(e){return safeError(res,e);}});
 app.post("/bootstrap/request",async(req,res)=>{try{const {viewer,role}=await reader(req.body);if(role!=="owner")return res.status(403).json({error:"Owner responsibility required"});return res.status(201).json(await createSetupRequest({organizationId:String(req.body?.organizationId??""),actorId:viewer.userId,actionId:requireActionId(req.body?.actionId)}));}catch(e){return safeError(res,e);}});
 app.post("/bootstrap/readiness",async(req,res)=>{try{await reader(req.body);return res.json(await validateSetupReadiness(String(req.body?.setupRequestId??"")));}catch(e){return safeError(res,e);}});
 app.post("/diagnostics/v1c-seed",async(req,res)=>{try{\n  if(process.env.MPP_ENABLE_V1C_FIXTURES!=="true")return res.status(404).json({error:"Diagnostic unavailable"});\n  const viewer=await deps.resolveTrustedAssignment(req.body?.key);\n  if(!viewer.assignmentFound||!deps.isActive(viewer.assignment.active)||viewer.activeLocation!==process.env.MPP_TEST_FIXTURE_LOCATION_ID)return res.status(404).json({error:"Diagnostic unavailable"});\n  const topology=await seedV1TestOrganization();return res.json({...topology,counts:await completeV1FixtureMatrix(topology.organizationId)});\n }catch(e){return safeError(res,e);}});
}
