const { Pool }=require("pg");let pool:any=null;function db(){if(pool)return pool;const connectionString=process.env.DATABASE_URL;if(!connectionString)throw new Error("DATABASE_URL is required");pool=new Pool({connectionString});return pool;}
export async function completeV1FixtureMatrix(organizationId:string){const c=await db().connect();try{await c.query("BEGIN");
 await c.query(`INSERT INTO mpp_team_visibility(person_id,team_id,location_id,state) SELECT p.person_id,t.team_id,t.location_id,'active' FROM mpp_people p JOIN mpp_teams t ON t.organization_id=p.organization_id WHERE p.organization_id=$1 AND p.test_user_serial IN('V1T_OWNER1_AB','V1T_RM1_AB') ON CONFLICT(person_id,team_id) DO UPDATE SET state='active',updated_at=NOW()`,[organizationId]);
 await c.query(`INSERT INTO mpp_team_visibility(person_id,team_id,location_id,state) SELECT p.person_id,t.team_id,t.location_id,'active' FROM mpp_people p JOIN mpp_person_location_access a USING(person_id) JOIN mpp_teams t ON t.location_id=a.location_id WHERE p.organization_id=$1 AND p.test_user_serial LIKE 'V1T_GM1_%' AND a.state='active' ON CONFLICT(person_id,team_id) DO UPDATE SET state='active',updated_at=NOW()`,[organizationId]);
 await c.query(`INSERT INTO mpp_team_visibility(person_id,team_id,location_id,state) SELECT person_id,team_id,location_id,'active' FROM mpp_team_management_assignments WHERE state='active' ON CONFLICT(person_id,team_id) DO UPDATE SET state='active',updated_at=NOW()`);
 await c.query(`INSERT INTO mpp_reporting_team_eligibility(person_id,team_id,location_id,state) SELECT p.person_id,t.team_id,t.location_id,'active' FROM mpp_people p JOIN mpp_teams t ON t.organization_id=p.organization_id WHERE p.organization_id=$1 AND p.test_user_serial IN('V1T_S02_T1_A','V1T_S02_T1_B') AND t.location_id=CASE WHEN p.test_user_serial LIKE '%_A' THEN 'V1T_LOCATION_A' ELSE 'V1T_LOCATION_B' END ON CONFLICT(person_id,team_id) DO UPDATE SET state='active',updated_at=NOW()`,[organizationId]);
 await c.query(`UPDATE mpp_people SET access_state='inactive',updated_at=NOW() WHERE organization_id=$1 AND test_user_serial IN('V1T_S04_T2_B','V1T_LEGACY_INACTIVE')`,[organizationId]);
 await c.query(`UPDATE mpp_person_location_access a SET state='inactive',updated_at=NOW() FROM mpp_people p WHERE a.person_id=p.person_id AND p.organization_id=$1 AND p.test_user_serial IN('V1T_S04_T2_B','V1T_LEGACY_INACTIVE')`,[organizationId]);
 const counts=(await c.query(`SELECT COUNT(*)::int people,COUNT(*) FILTER(WHERE access_state<>'inactive')::int intended_active,COUNT(*) FILTER(WHERE access_state='inactive')::int inactive FROM mpp_people WHERE organization_id=$1`,[organizationId])).rows[0];await c.query("COMMIT");return counts;
 }catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();}}
